import { TestHelper } from '../utils';
import { ErrorTypes } from '../../src/server/utils/errors';
import request from 'supertest';
import { User, Project, Status } from '../../src/models';
const testHelper = new TestHelper();
const serverUrl = testHelper.getServerUrl();
let apiRoute = '/projects/:projectId/stories';

describe('Story Create', () => {
  describe(`POST ${apiRoute}`, () => {
    let adminUser: User;
    let adminAuthToken: string;
    let managerUser: User;
    let managerAuthToken: string;
    let developerUser: User;
    let developerAuthToken: string;
    let nonMember: User;
    let nonMemberAuthToken: string;
    let viewerMember: User;
    let viewerAuthToken: string;
    let testProject: Project;
    let inactiveProject: Project;
    let existingStatus: Status;
    let payload: {
      title: unknown;
      details: unknown;
      status: unknown;
      ownedBy: unknown;
    };

    beforeAll(async () => {
      adminUser = await testHelper.createTestUser();
      adminAuthToken = testHelper.generateToken(adminUser);

      managerUser = await testHelper.createTestUser();
      managerAuthToken = testHelper.generateToken(managerUser);

      developerUser = await testHelper.createTestUser();
      developerAuthToken = testHelper.generateToken(developerUser);

      nonMember = await testHelper.createTestUser();
      nonMemberAuthToken = testHelper.generateToken(nonMember);

      viewerMember = await testHelper.createTestUser();
      viewerAuthToken = testHelper.generateToken(viewerMember);

      testProject = await testHelper.createTestProject(adminUser);
      await testProject.createMembership({
        userId: viewerMember.id,
        createdBy: adminUser.id,
      });
      await testProject.createMembership({
        userId: managerUser.id,
        createdBy: adminUser.id,
        isProjectManager: true,
      });
      await testProject.createMembership({
        userId: developerUser.id,
        createdBy: adminUser.id,
        isProjectDeveloper: true,
      });
      existingStatus = await testProject.createStatus({ name: 'ExistingStatus' });

      inactiveProject = await testHelper.createTestProject(adminUser);
      inactiveProject.isActive = false;
      await inactiveProject.save();
    });

    afterAll(async () => {
      await testHelper.removeTestData();
    });

    beforeEach(() => {
      apiRoute = `/projects/${testProject.id}/stories`;
      payload = {
        title: 'Unit Test Story',
        details: 'Autogenerated via unit testing',
        status: undefined,
        ownedBy: undefined,
      };
    });

    it('should reject requests when x-auth-token is missing', (done) => {
      request(serverUrl).post(apiRoute).send(payload).expect(
        400,
        {
          error: 'x-auth-token header is missing from input',
          errorType: ErrorTypes.VALIDATION,
        },
        done,
      );
    });

    it('should reject requests when projectId is not a valid UUID', (done) => {
      apiRoute = '/projects/somethingInvalid/stories';
      request(serverUrl).post(apiRoute).set('x-auth-token', adminAuthToken).expect(
        400,
        {
          error: 'requested project id is not valid',
          errorType: ErrorTypes.VALIDATION,
        },
        done,
      );
    });

    it('should reject requests when the requested project does not exist', (done) => {
      apiRoute = `/projects/${testHelper.generateUUID()}/stories`;
      request(serverUrl).post(apiRoute).set('x-auth-token', adminAuthToken).expect(
        404,
        {
          error: 'requested project not found',
          errorType: ErrorTypes.NOT_FOUND,
        },
        done,
      );
    });

    it('should reject requests when the requested project is not active', (done) => {
      apiRoute = `/projects/${inactiveProject.id}/stories`;
      request(serverUrl).post(apiRoute).set('x-auth-token', adminAuthToken).expect(
        404,
        {
          error: 'requested project not found',
          errorType: ErrorTypes.NOT_FOUND,
        },
        done,
      );
    });

    it('should reject requests when the authenticated user is not a project member', (done) => {
      request(serverUrl).post(apiRoute).set('x-auth-token', nonMemberAuthToken).expect(
        401,
        {
          error: 'you do not have permission to create stories for this project',
          errorType: ErrorTypes.AUTHORIZATION,
        },
        done,
      );
    });

    it('should reject requests when the authenticated user is a viewer', (done) => {
      request(serverUrl).post(apiRoute).set('x-auth-token', viewerAuthToken).expect(
        401,
        {
          error: 'you do not have permission to create stories for this project',
          errorType: ErrorTypes.AUTHORIZATION,
        },
        done,
      );
    });

    it('should reject requests when title is missing from input', (done) => {
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send({})
        .expect(
          400,
          {
            error: 'title is missing from input',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should reject requests when title is not a string', (done) => {
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send({
          title: 21384902,
        })
        .expect(
          400,
          {
            error: 'title must be a string',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should reject requests when title is less than 1 character', (done) => {
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send({
          title: '',
        })
        .expect(
          400,
          {
            error: 'title must be 1 - 150 characters in length',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should reject requests when title is more than 150 character', (done) => {
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send({
          title: Array(151).fill('a').join(''),
        })
        .expect(
          400,
          {
            error: 'title must be 1 - 150 characters in length',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should reject requests when details is not a string', (done) => {
      payload.details = false;
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send(payload)
        .expect(
          400,
          {
            error: 'details must be a string',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should reject requests when status is not a string', (done) => {
      payload.status = ['wads'];
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send(payload)
        .expect(
          400,
          {
            error: 'status must be a string',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should reject requests when status is not a valid UUID', (done) => {
      payload.status = 'thisAintRight';
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send(payload)
        .expect(
          400,
          {
            error: 'requested status id is not valid',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should reject requests when status is not found', (done) => {
      payload.status = testHelper.generateUUID();
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send(payload)
        .expect(
          404,
          {
            error: 'requested status not found',
            errorType: ErrorTypes.NOT_FOUND,
          },
          done,
        );
    });

    it('should reject requests when ownedBy is not a string', (done) => {
      payload.ownedBy = {};
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send(payload)
        .expect(
          400,
          {
            error: 'ownedBy must be a string',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should reject requests when the ownedBy user does not exist', (done) => {
      payload.ownedBy = 'doesNotExistLol';
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send(payload)
        .expect(
          404,
          {
            error: 'ownedBy user does not exist',
            errorType: ErrorTypes.NOT_FOUND,
          },
          done,
        );
    });

    it('should reject requests when the ownedBy user is not a project member', (done) => {
      payload.ownedBy = nonMember.displayName;
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send(payload)
        .expect(
          400,
          {
            error: 'ownedBy user must be a project member',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should reject requests when the ownedBy user is a viewer', (done) => {
      payload.ownedBy = viewerMember.displayName;
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send(payload)
        .expect(
          400,
          {
            error: 'ownedBy user must have developer permissions or higher',
            errorType: ErrorTypes.VALIDATION,
          },
          done,
        );
    });

    it('should successfully create a story for an admin', (done) => {
      payload.status = existingStatus.id;
      payload.ownedBy = developerUser.displayName;
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', adminAuthToken)
        .send(payload)
        .expect(200)
        .end(async (err, res) => {
          if (err) {
            return done(err);
          }

          const { message, story } = res.body;
          // Ensure the story was actually created.
          const createdTestStory = await testProject.getStory({
            where: { id: story.id },
          });
          if (!createdTestStory) {
            return done('story was not found in database');
          }

          expect(message).toBe('story has been successfully created');
          expect(story).toEqual({
            id: createdTestStory.id,
            title: payload.title,
            details: payload.details,
            status: {
              id: existingStatus.id,
              name: existingStatus.name,
            },
            project: {
              id: testProject.id,
              name: testProject.name,
            },
            createdOn: createdTestStory.createdOn.toISOString(),
            createdBy: {
              username: adminUser.username,
              displayName: adminUser.displayName,
            },
            ownedBy: {
              username: developerUser.username,
              displayName: developerUser.displayName,
            },
          });
          done();
        });
    });

    it('should successfully create a story for a manager', (done) => {
      payload.title = 'Story by Manager';
      payload.details = 'Some details that are super important';
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', managerAuthToken)
        .send(payload)
        .expect(200)
        .end(async (err, res) => {
          if (err) {
            return done(err);
          }

          const { message, story } = res.body;
          // Ensure the story was actually created.
          const createdTestStory = await testProject.getStory({
            where: { id: story.id },
          });
          if (!createdTestStory) {
            return done('story was not found in database');
          }

          expect(message).toBe('story has been successfully created');
          expect(story).toEqual({
            id: createdTestStory.id,
            title: payload.title,
            details: payload.details,
            project: {
              id: testProject.id,
              name: testProject.name,
            },
            createdOn: createdTestStory.createdOn.toISOString(),
            createdBy: {
              username: managerUser.username,
              displayName: managerUser.displayName,
            },
            ownedBy: null,
            status: null,
          });
          done();
        });
    });

    it('should successfully create a story for a developer', (done) => {
      payload.title = 'Story by Developer';
      payload.details = undefined;
      request(serverUrl)
        .post(apiRoute)
        .set('x-auth-token', developerAuthToken)
        .send(payload)
        .expect(200)
        .end(async (err, res) => {
          if (err) {
            return done(err);
          }

          const { message, story } = res.body;
          // Ensure the story was actually created.
          const createdTestStory = await testProject.getStory({
            where: { id: story.id },
          });
          if (!createdTestStory) {
            return done('story was not found in database');
          }

          expect(message).toBe('story has been successfully created');
          expect(story).toEqual({
            id: createdTestStory.id,
            title: payload.title,
            details: null,
            project: {
              id: testProject.id,
              name: testProject.name,
            },
            createdOn: createdTestStory.createdOn.toISOString(),
            createdBy: {
              username: developerUser.username,
              displayName: developerUser.displayName,
            },
            ownedBy: null,
            status: null,
          });
          done();
        });
    });
  });
});
