name: PR Checks
run-name: PR Checks
on: [pull_request]
jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install node_modules
        run: npm install
      - name: Run eslint
        run: npx eslint src
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install node_modules
        run: npm install
      - name: Create dummy db config file
        run: touch src/config/db.ts
      - name: Populate dummy db config file
        run: |
          echo "
          export const DB_USERNAME = 'dummy';
          export const DB_PASSWORD = 'dummy';
          export const DB_HOSTNAME = 'localhost';
          export const DB_PORT = '5432';
          export const DB_NAME = 'dummy';" > src/config/db.ts
      - name: Create dummy auth config file
        run: touch src/config/auth.ts
      - name: Populate dummy auth config file
        run: |
          echo "
          export const SECRET = 'dummy_secret';
          export const SALT_ROUNDS = 10;" > src/config/auth.ts
      - name: Build app
        run: npm run build
